import json,subprocess
from pathlib import Path
root=Path('/tmp/labyrinth-perf-2026-09-17')
repo=Path('/Users/borgerding/workspace/Labyrinth.worktrees/thorough-steam-deck-performance-pass-across-varied-gameplay-and-animatio')
a=json.loads((root/'sept18-final4-analysis.json').read_text())
commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip()
lines=['# Completed native combat validation — 18 September 2026','',f'The previously pending native test has now run on the final runtime sources at `{commit}`. This phase continues from `365dc25bd28385a80e20b7925f96a115024b3f7f`, whose production is the earlier tracker cleanup. It adds measured reductions in enemy-route allocation, locked-hand capture/restore, repeated card-tree setup, procedural effect calculations, and profiler attribution work. All fourteen final native runs complete with zero focus violations and zero semantic errors.','',
'**This does not establish hitch-free play or Steam Deck frame rates.** The tables below include the remaining isolated spikes and measurements that did not improve. The earlier pass made the larger action-latency gains; this follow-up closes the missing native validation and reduces several remaining costs, with mixed whole-frame results. No renderer resolution, MSAA, effect population, authored animation duration, persistence boundary, or input contract was reduced.','',
'This report supersedes the pending-test status in the [earlier native checkpoint](performance_native_followup_2026_09_18.md). That report remains historical evidence for its own commits. The [new proof manifest](proofs/performance-2026-09-17/native-completion/manifest.json) binds accepted reports to the final runtime using recursive source hashes and archives raw distributions, logs, comparison output, images, and source guards. Candidate measurements were captured before committing and therefore retain HEAD 365dc25 plus dirty status; they are linked to this commit by content hashes, not by relabeling their recorded HEAD.','',
'## Changes and isolated measurements','',
'- Enemy route queries compute nearest footprint distance directly and reuse one owned hypothetical enemy dictionary during a search. They preserve route order, tie breaks, arbitrary footprints, sentinel behavior, RNG and state ownership. The isolated native enemy matrix reduced future-search CPU by 32–39%; maximum simulation slices fell from 12.75/19.84/16.73 ms to 11.37/15.44/13.83 ms across dragon support, specialists and swarm. Whole-frame tails did not consistently improve in that component pair.','- Locked-hand caching moves only the renderer canvas item to the retained target. Controls keep their actual parents, themes, and layout. This removes tree/theme work during capture and restore. In the isolated native pair, capture fell from 2.48–2.94 ms to 0.92–0.94 ms; restore from 2.92–3.28 ms to 0.58–0.67 ms. Pending fan layout is settled before capturing. Geometry, visibility, hierarchy, appearance and lifetime changes restore live rendering; animated cards and unsupported ancestor composition bypass caching.','- The existing two-card proxy pool retains hidden disabled controls in their stable combat FX host. Reuse restores geometry and state without tree re-entry. Mounting explicitly restores fresh launch sibling order, including equal-z overlapping cards leased from the LIFO pool. Other hosts and noncombat leases retain the previous detach behavior.','- Procedural FX retain exact float64 seed values in a fixed 8 KiB cache, reuse bounded seed-only rock coefficients for authored spell seeds, and hoist invariant bolt length. Arbitrary rubble seeds retain the original inline allocation path. The hash microbenchmark is faster, but the hash-only combat pair did not establish a meaningful whole-action improvement. Fire-pose caching experiments were reverted because the measured benefit was negligible.','- Surface abilities prepare optional hand/playability and forecast queries during their existing animation, then adopt them only after the original commit/save boundary and exact full-state equality. Partial or changed-state jobs use the synchronous fallback; the animation never waits for preparation. This targets the repeated Prismatic Instinct completion spike found by the final3 repetition. Removing proxy retention did not remove that spike in a separate isolation run.',
'- The phase partitioner detects properly nested intervals in one sorted scan and skips its general crossed-interval machinery in that case. The original general path remains for crossing spans. Frozen-reference comparisons cover complete outputs for 4,800 cases; nested microbenchmarks were about 19% faster. Instrumentation cadence and attribution semantics remain unchanged.','',
'Component pairs are archived as diagnostics with their own intermediate source snapshots. Their numbers explain the specific work removed; the final-build frame results are only the final4 pairs below.','',
'## Measurement conditions','',
'Apple M5 Pro, macOS 26.3.1 arm64, Godot 4.6.1, Metal/mobile, production 4× MSAA, actual native 1920×1080 and 100% UI scale. Tests run serially in the foreground, without concurrent CPU regression suites. Frame intervals end at frame_post_draw. Each pair has matching workload, harness, instrumentation, warmup, motion setting and dimensions. GPU timers return zero and the texture-memory monitor returns an overflow sentinel; neither is interpreted as a real measurement.','',
'The detailed full matrix includes the seven-card cap, varied specialist/dragon/swarm encounters, preview and hover interactions, all fixture cards, abilities, movement, enemy rounds, turn unlock, surfaces and overlapping effects. Focused normal-motion repeats reverse baseline/candidate order. A second reduced-motion pair also reverses order to investigate the first pair’s mixed tails. Reduced motion retains its authored static impact. Early depth-2 combat has five cards and three enemies; middle depth-7 combat has six cards, five enemies, relics, skills, illusion, surfaces, trap, loot and props. These ordinary scenarios complement the heavy matrix.','',
'## Final native frame results','',
'Values are milliseconds, before → after relative to the already optimized 365dc25 checkpoint. The comparison JSON retains medians, p95, p99, maximum, threshold misses, action duration, animation contracts, memory and node totals. Maxima are isolated samples and vary between repetitions; improvement in one subsystem does not imply every frame statistic improves.','']
def display(key):return key.split('.',1)[1].replace('_',' ').title()
def table(pair):
 lines.extend(['| Action / encounter | Worst frame (ms) | p95 (ms) | Frames >16.67 ms |','| --- | ---: | ---: | ---: |'])
 for key,m in a['pairs'][pair]['metrics'].items():
  conv=lambda name:f"{m[name]['base']:.2f} → {m[name]['candidate']:.2f}"
  count=m.get('frames_over_16_67_ms');ct=f"{count['base']} → {count['candidate']}" if count else '—'
  lines.append(f"| {display(key)} | {conv('max')} | {conv('p95')} | {ct} |")
 lines.append('')
for pair,title in [('early','Ordinary early combat'),('middle','Ordinary middle combat'),('full','Full matrix, detailed instrumentation')]:
 lines.extend(['### '+title,'']);table(pair)
lines.extend(['### Focused repeats, normal motion','', '| Action | Baseline worst, two orders (ms) | Candidate worst, two orders (ms) | Baseline p95 | Candidate p95 |','| --- | ---: | ---: | ---: | ---: |'])
for key,m in a['pairs']['tail-a']['metrics'].items():
 n=a['pairs']['tail-b']['metrics'][key]
 vals=lambda metric,side:f"{m[metric][side]:.2f}, {n[metric][side]:.2f}"
 lines.append(f"| {display(key)} | {vals('max','base')} | {vals('max','candidate')} | {vals('p95','base')} | {vals('p95','candidate')} |")
lines.extend(['','### Reduced motion','']);table('reduced')
lines.extend(['### Reduced motion, reverse-order follow-up','']);table('reduced-repeat')
lines.extend(['## Remaining costs and interpretation','',
'Action-completion and turn-transition spikes remain. Detailed traces attribute substantial CPU to hand/playability refresh, board submission and UI layout, plus synchronous durable checkpoint/analytics transactions. The heaviest overlapping Wildfire case also has sustained animation frames above 16.67 ms. These are known costs in the final data, not a promise that Deck play is already smooth. Profiling and optimizing storage further must preserve synchronous durability, recovery and acknowledgement boundaries; this phase does not skip saves or reuse prior-transaction inspections.','',
'The reverse-order reduced-motion check confirms a small Wildfire p95 regression: 10.54/10.86 → 12.27/12.16 ms. It is not dismissed as noise. In those same runs, worst frames fall 34.32/30.66 → 26.74/24.69 ms, total action time falls 909/917 → 898/890 ms, and frames over 16.67 ms are 4/3 → 3/3. The p95 selects the sixth-slowest interval in these roughly 100-frame actions; raw samples place the candidate value at an early/late transition, while the sustained static-effect samples remain around 8–10 ms. This is an explicit tradeoff: lower severe transition peaks and shorter completion, with a 1.3–1.7 ms sub-budget p95 increase. The exact source of that small transition increase is not isolated; GPU counters cannot resolve it on this host. Reduced-motion Quick Wits also retains a worse maximum in both orders despite similar p95 and unchanged budget-miss counts.', '',
'The final comparison must be assessed alongside the earlier pass rather than treated as another across-the-board reduction. Several p95 values, missed-frame counts and maxima are flat or worse; all are retained above. A real Steam Deck foreground capture remains necessary to establish its frame budget, thermal behavior and GPU costs. The native Mac result closes the delayed validation, but cannot substitute for target-hardware evidence.','',
'## Memory and lifecycle',''])
full=a['pairs']['full']
for key,m in full['memory'].items():lines.append(f"- `{key}`: {m['base']:,} → {m['candidate']:,} bytes ({m['candidate']-m['base']:+,}).")
for key,m in full['nodes'].items():lines.append(f"- `{key}`: {m['base']} → {m['candidate']}.")
lines.extend(['','The hand target remains one retained target per host; the proxy pool remains limited to two instances; procedural hash storage is fixed at 8 KiB and rock coefficients at 32 entries. Reported whole-process memory includes unrelated engine caches and differs between runs; it is not an isolated allocation cost. Host replacement, active/pending capture, hierarchy removal and scene teardown have explicit checks.','',
'## Correctness and rendering proof','',
'- Full Godot regression suite and fifteen focused checks pass on source-bound final files. Focused coverage includes route allocation, phase partitioning, FX hashes/cache bounds, proxy reuse/order, committed hand queries, hover coalescing, combat boundaries, forced movement, analytics context, profile normalization, save/resume recovery, surface analytics, surface presentation and card draw/hand flow.','- The actual surface-ability coroutine passes normal, reduced-motion and cancelled-preparation cases. Normal and reduced modes adopt seven prepared cards and one forecast; cancellation adopts nothing and uses the synchronous path. The old committed state is checked on every suspended animation frame. Disk state is checked immediately after scheduling and at completion; the final live and saved combat state match the complete engine result with existing analytics cursor staging. The guard checks termination; native action-duration evidence is separate.',
'- Route equivalence covers 13,800 comparisons, 990 plans and 495 complete turns across all 31 enemy types and authored intent variants. Complete state, RNG, logs, steps and ownership match a frozen reference. Some dense/large-footprint stress cases deliberately overlap actors; the full suite supplies coherent authored pathfinding and combat checks as well.','- Sixteen native image pairs cover all five elements, ground/impact/rear/front/release/travel, eight progress values, full/reduced motion, fractional positions/scales, ribbon edge cases, and rock seeds across negative/large and cache-boundary values. Twelve pairs are byte-identical; the remaining four differ by a single 8-bit step in at most two channels across 1920×1080. All 32 images are retained.','- Fresh native hand-cache proof covers content changes, three retained-target captures, fractional transforms, alpha-ancestor fallback, card tint/ancestor opacity, nested visibility, geometry changes, input locking, pending layout, overlapping captures, active and pending host deletion, hand detach/reattach, live animation bypass and scene teardown. Mutations restore before drawing. The cached snapshot contract covers current CardWidget refresh paths; arbitrary future nested renderer-only material/tint changes must participate in invalidation or bypass.','- The native card-flow probe covers opening and overlapping draws, settled authoritative handoff, reduced motion and real next-turn unlock. Representative images were inspected at 1920×1080; automated semantic checks accompany them.','- Enemy reference digests, step counts and activation counts match in every paired scenario. Authored animation durations/frame counts/run counts match wherever instrumented; actual skipped-frame counts remain in the comparison.','',
'The first full suite in this phase caught three FX-cleanup failures. Nonproxy leftovers now detach synchronously; the motion regression counts an FX proxy as retired only when it belongs to the bounded pool, is hidden and has processing disabled. Unowned, visible or active ghosts still fail. The full suite was rerun after these corrections.',
'Pre-existing ObjectDB-at-exit warnings in scene-based probes and deliberate corrupt-save/failed-write messages in recovery tests are retained in logs. Invalid focus runs and superseded experiments are separately classified and excluded from final timing tables.','',
'## Reproduce and inspect','',
'The proof archive includes the exact serial run drivers and analysis. Invoke repository runners from the isolated task worktree. `run_final4_native.py` documents all environment settings; its local paths must be adjusted when reproduced elsewhere. `tools/performance_pass.py compare BASE CANDIDATE` checks pair compatibility.','',
'The inspection fixture regenerates and verifies a separate pre-action combat save with ooze/droplets/gaoler, seven movement/attack cards and fire/ice/electrified surfaces. Its self-healing launcher is recorded in the final handoff. The branch remains local and unpublished pending user inspection and explicit publication approval.'])
(repo/'spec/performance_native_completion_2026_09_18.md').write_text('\n'.join(lines)+'\n')
# Keep the prior report historical; add a clear forward pointer without rewriting its old measurements.
p=repo/'spec/performance_native_followup_2026_09_18.md';s=p.read_text();notice='> Update: the previously pending native validation is complete; see [final native validation and additional hitch work](performance_native_completion_2026_09_18.md) for the current source-bound results and remaining limits. The checkpoint below is historical.\n\n'
if notice not in s:s=s.replace('\n\n','\n\n'+notice,1);p.write_text(s)
print(repo/'spec/performance_native_completion_2026_09_18.md')
