extends RefCounted

const Base = preload("res://tests/suites/move_attack_shortcut_suite.gd")
const Combat = preload("res://scripts/combat_engine.gd")
const RunScene = preload("res://scripts/run_scene.gd")
const INVALID := Vector2i(-1, -1)
const ENEMY := Vector2i(3, 3)
const WEST := Vector2i(2, 3)
const SOUTH := Vector2i(3, 4)

static func run(expect: Callable) -> void:
	var combat := Combat.new()
	var state: Dictionary = Base._combat_state(combat, "sidestep_slash", ENEMY, 9292026)
	var scene := RunScene.new()
	scene.set("_combat_state", state)
	var preview: Dictionary = _preview(scene, combat, state)
	var baseline: Dictionary = scene.call("_shortcut_plan_for_tile", preview, ENEMY)
	var approach = scene.get("_move_attack_approach")
	for endpoint: Vector2i in [WEST, SOUTH, WEST]:
		approach.observe(endpoint, scene)
		approach.observe(ENEMY, scene)
		var plan: Dictionary = scene.call("_shortcut_plan_for_tile", preview, ENEMY)
		expect.call(plan.get("move_tile") == endpoint, "Re-entering the enemy chooses the most recent legal endpoint %s" % endpoint)
		expect.call((plan.get("path_tiles", []) as Array).back() == endpoint, "Arrow ends on the chosen attack position")
		approach.observe(ENEMY, scene)
		expect.call((scene.call("_shortcut_plan_for_tile", preview, ENEMY) as Dictionary).get("move_tile") == endpoint, "Repeated same-tile motion retains the entry position")
	for invalid_entry: Vector2i in [INVALID, Vector2i(0, 0), Vector2i(7, 7), Vector2i(1, 4)]:
		approach.observe(invalid_entry, scene)
		approach.observe(ENEMY, scene)
		expect.call((scene.call("_shortcut_plan_for_tile", preview, ENEMY) as Dictionary).get("move_tile") == baseline.get("move_tile"), "Off-board, wall, unreachable and out-of-attack-range entry uses the default")
	approach.observe(WEST, scene)
	approach.observe(ENEMY, scene)
	var first_key: String = scene.call("_pass_preview_key")
	approach.observe(SOUTH, scene)
	approach.observe(ENEMY, scene)
	expect.call(first_key != str(scene.call("_pass_preview_key")), "Same enemy approached differently invalidates cached turn consequences")
	scene.call("_mark_preview_selection_changed")
	expect.call(approach.entry == INVALID, "Card/action changes clear stale approach")
	approach.observe(WEST, scene)
	approach.observe(ENEMY, scene)
	scene.call("_mark_combat_preview_state_changed")
	expect.call(approach.entry == INVALID, "Committed world changes clear stale approach")
	# Adjacent targets can still be deliberately approached from farther away.
	var adjacent: Dictionary = Base._combat_state(combat, "sidestep_slash", SOUTH, 9292027)
	scene.set("_combat_state", adjacent)
	scene.call("_mark_combat_preview_state_changed")
	preview = _preview(scene, combat, adjacent)
	approach.observe(Vector2i(3, 5), scene)
	approach.observe(SOUTH, scene)
	expect.call((scene.call("_shortcut_plan_for_tile", preview, SOUTH) as Dictionary).get("move_tile") == Vector2i(3, 5), "An explicit longer approach overrides the automatic stay-put strike")
	approach.observe(Base.PLAYER_START, scene)
	approach.observe(SOUTH, scene)
	expect.call((scene.call("_shortcut_plan_for_tile", preview, SOUTH) as Dictionary).get("move_target") == INVALID, "Entering from the player preserves the no-movement strike")
	# An explicit legal choice can accept danger that the automatic route avoids.
	var risky: Dictionary = state.duplicate(true)
	risky["traps"] = [{"id":"approach_risk", "pos":WEST, "element":"fire", "damage":2, "triggered":false}]
	scene.set("_combat_state", risky)
	scene.call("_mark_combat_preview_state_changed")
	preview = _preview(scene, combat, risky)
	approach.observe(WEST, scene)
	approach.observe(ENEMY, scene)
	var risky_plan: Dictionary = scene.call("_shortcut_plan_for_tile", preview, ENEMY)
	expect.call(risky_plan.get("move_tile") == WEST, "A survivable hazardous endpoint remains the player's choice")
	expect.call(not (risky_plan.get("movement_risk_chips", []) as Array).is_empty(), "Chosen hazardous approach retains its risk preview")
	# Trap contact must be simulated before accepting an endpoint.
	var hazardous: Dictionary = state.duplicate(true)
	hazardous["traps"] = [{"id":"approach_lethal", "pos":WEST, "element":"fire", "damage":100, "triggered":false}]
	scene.set("_combat_state", hazardous)
	scene.call("_mark_combat_preview_state_changed")
	preview = _preview(scene, combat, hazardous)
	var hazard_default: Dictionary = scene.call("_shortcut_plan_for_tile", preview, ENEMY)
	approach.observe(WEST, scene)
	approach.observe(ENEMY, scene)
	var hazard_plan: Dictionary = scene.call("_shortcut_plan_for_tile", preview, ENEMY)
	expect.call(hazard_plan.get("move_tile") == hazard_default.get("move_tile"), "A lethal approach cannot advertise an impossible follow-up attack")
	# Multi-cell actor interiors are not new entry positions.
	state["enemies"][0]["footprint"] = Vector2i(2, 1)
	scene.set("_combat_state", state)
	scene.call("_mark_combat_preview_state_changed")
	approach.observe(WEST, scene)
	approach.observe(ENEMY, scene)
	approach.observe(Vector2i(4, 3), scene)
	expect.call(approach.entry == WEST, "Moving within a large enemy footprint retains the approach")
	# Blink shares the choice without fabricating a walking route.
	state["enemies"][0]["footprint"] = Vector2i.ONE
	scene.call("_mark_combat_preview_state_changed")
	var actions: Array = [{"type":"blink", "range":3}, {"type":"melee", "range":1, "damage":5}]
	preview = scene.call("_card_preview_from_state", "sidestep_slash", state, actions, 0)
	approach.observe(Vector2i(4, 3), scene)
	approach.observe(ENEMY, scene)
	var blink: Dictionary = scene.call("_shortcut_plan_for_tile", preview, ENEMY)
	expect.call(blink.get("move_tile") == Vector2i(4, 3) and blink.get("path_tiles") == [Vector2i(4, 3)], "Blink uses the chosen legal endpoint and a destination-only preview")
	# Existing Umbra policy cannot be bypassed by the new preference.
	var hidden: Dictionary = Base._visible_terrain_state(combat)
	scene.set("_combat_state", hidden)
	scene.call("_mark_combat_preview_state_changed")
	preview = _preview(scene, combat, hidden)
	approach.observe(Vector2i(2, 2), scene)
	approach.observe(Vector2i(2, 1), scene)
	expect.call((scene.call("_shortcut_plan_for_tile", preview, Vector2i(2, 1)) as Dictionary).is_empty(), "Approach preference does not reveal an unseen enemy")
	scene.free()

static func _preview(scene: Node, combat: Combat, state: Dictionary) -> Dictionary:
	var prepared: Dictionary = combat.prepare_player_card(state, 0, "play")
	return scene.call("_card_preview_from_state", "sidestep_slash", prepared, combat.card_play_actions("sidestep_slash", prepared), 0)
