#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_CONFIG_PATH="${PROJECT_ROOT}/steam/steam_build_config.env"
DEFAULT_GODOT_BINARY="/Applications/Godot.app/Contents/MacOS/Godot"
DEFAULT_STEAMCMD_URL="https://steamcdn-a.akamaihd.net/client/installer/steamcmd_osx.tar.gz"
STEAMCMD_DIR="${PROJECT_ROOT}/.steam/sdk/tools/ContentBuilder/builder_osx"
STEAMCMD_SH="${STEAMCMD_DIR}/steamcmd.sh"
HOST_ARCH="$(uname -m)"
BUILD_ROOT="${PROJECT_ROOT}/build/steam"
CONTENT_ROOT="${BUILD_ROOT}/content"
STEAMPIPE_ROOT="${BUILD_ROOT}/steampipe"
STEAMPIPE_SCRIPT_ROOT="${STEAMPIPE_ROOT}/scripts"
STEAMPIPE_OUTPUT_ROOT="${STEAMPIPE_ROOT}/output"
EXPORT_STAGING_ROOT="${PROJECT_ROOT}/.steam/export_staging"
EXPORT_PROJECT_ROOT="${PROJECT_ROOT}/.steam/export_project"
DEV_EXPORT_PATH_PATTERN='^res://(\.codex|output|playtest|spec|tests|tmp|tools)/'

CONFIG_PATH="${DEFAULT_CONFIG_PATH}"
GODOT_BINARY="${DEFAULT_GODOT_BINARY}"
MODE="all"
TARGETS_CSV="main,playtest"
PLATFORMS_CSV="auto"
PREVIEW_BUILD=0
DRY_RUN=0
DESC_OVERRIDE=""
MAIN_BRANCH_OVERRIDE=""
PLAYTEST_BRANCH_OVERRIDE=""
STEAM_USERNAME_OVERRIDE=""

TARGET_MAIN=0
TARGET_PLAYTEST=0
EXPORT_MACOS=0
EXPORT_WINDOWS=0
EXPORT_LINUX=0

STEAM_BUILDER_USERNAME=""
STEAM_MAIN_APP_ID=0
STEAM_MAIN_BRANCH="default"
STEAM_MAIN_DEPOT_MACOS=0
STEAM_MAIN_DEPOT_WINDOWS=0
STEAM_MAIN_DEPOT_LINUX=0
STEAM_PLAYTEST_APP_ID=0
STEAM_PLAYTEST_BRANCH="default"
STEAM_PLAYTEST_DEPOT_MACOS=0
STEAM_PLAYTEST_DEPOT_WINDOWS=0
STEAM_PLAYTEST_DEPOT_LINUX=0
STEAM_PRODUCT_NAME="Escape the Umbra"
STEAM_MACOS_APP_NAME="Escape the Umbra.app"
STEAM_WINDOWS_EXECUTABLE_NAME="Escape the Umbra.exe"
STEAM_LINUX_EXECUTABLE_NAME="Escape the Umbra.x86_64"
STEAMCMD_URL="${DEFAULT_STEAMCMD_URL}"
GODOT_EXPORT_TEMPLATES_URL=""

usage() {
	cat <<'EOF'
Usage:
  ./scripts/build_and_upload_steam.sh [options]

Options:
  --config PATH             Config file to source. Defaults to steam/steam_build_config.env
  --targets LIST            Comma-separated: main, playtest. Defaults to main,playtest
  --platforms LIST          Comma-separated: macos, windows, linux, auto. Defaults to auto
  --export-only             Export builds but do not upload to Steam
  --upload-only             Upload existing exported builds without re-exporting
  --preview                 Generate a Steam preview build instead of uploading content
  --desc TEXT               Override the autogenerated Steam build description
  --main-branch NAME        Override STEAM_MAIN_BRANCH for this run
  --playtest-branch NAME    Override STEAM_PLAYTEST_BRANCH for this run
  --godot-binary PATH       Override the Godot binary for this run
  --steam-username NAME     Override STEAM_BUILDER_USERNAME for this run
  --dry-run                 Export and generate SteamPipe scripts, but skip SteamCMD
  -h, --help                Show this help

Examples:
  ./scripts/build_and_upload_steam.sh --export-only
  ./scripts/build_and_upload_steam.sh --targets playtest
  ./scripts/build_and_upload_steam.sh --targets main --main-branch internal
  ./scripts/build_and_upload_steam.sh --targets main,playtest --platforms macos,windows,linux
  ./scripts/build_and_upload_steam.sh --preview --targets playtest
EOF
}

log() {
	printf '[steam-build] %s\n' "$*"
}

fail() {
	printf '[steam-build] ERROR: %s\n' "$*" >&2
	exit 1
}

normalize_csv_item() {
	printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]'
}

is_positive_int() {
	case "$1" in
		''|*[!0-9]*)
			return 1
			;;
		0)
			return 1
			;;
		*)
			return 0
			;;
	esac
}

vdf_escape() {
	local value="$1"
	value=${value//\\/\\\\}
	value=${value//\"/\\\"}
	printf '%s' "${value}"
}

ensure_dir() {
	mkdir -p "$1"
}

prepare_export_project() {
	log "Preparing sanitized export project."
	rm -rf "${EXPORT_PROJECT_ROOT}"
	ensure_dir "${EXPORT_PROJECT_ROOT}"

	rsync -a --delete \
		--exclude '/.git/' \
		--exclude '/.godot/' \
		--exclude '/.import/' \
		--exclude '/.steam/' \
		--exclude '/.codex/' \
		--exclude '/build/' \
		--exclude '/output/' \
		--exclude '/playtest/' \
		--exclude '/spec/' \
		--exclude '/tests/' \
		--exclude '/tmp/' \
		--exclude '/tools/' \
		--exclude '.DS_Store' \
		"${PROJECT_ROOT}/" "${EXPORT_PROJECT_ROOT}/"
}

parse_args() {
	while [[ $# -gt 0 ]]; do
		case "$1" in
			--config)
				CONFIG_PATH="$2"
				shift 2
				;;
			--targets)
				TARGETS_CSV="$2"
				shift 2
				;;
			--platforms)
				PLATFORMS_CSV="$2"
				shift 2
				;;
			--export-only)
				MODE="export-only"
				shift
				;;
			--upload-only)
				MODE="upload-only"
				shift
				;;
			--preview)
				PREVIEW_BUILD=1
				shift
				;;
			--desc)
				DESC_OVERRIDE="$2"
				shift 2
				;;
			--main-branch)
				MAIN_BRANCH_OVERRIDE="$2"
				shift 2
				;;
			--playtest-branch)
				PLAYTEST_BRANCH_OVERRIDE="$2"
				shift 2
				;;
			--godot-binary)
				GODOT_BINARY="$2"
				shift 2
				;;
			--steam-username)
				STEAM_USERNAME_OVERRIDE="$2"
				shift 2
				;;
			--dry-run)
				DRY_RUN=1
				shift
				;;
			-h|--help)
				usage
				exit 0
				;;
			*)
				fail "Unknown argument: $1"
				;;
		esac
	done
}

load_config() {
	[[ -f "${CONFIG_PATH}" ]] || fail "Missing config file: ${CONFIG_PATH}"
	# shellcheck disable=SC1090
	source "${CONFIG_PATH}"

	if [[ -n "${STEAM_USERNAME_OVERRIDE}" ]]; then
		STEAM_BUILDER_USERNAME="${STEAM_USERNAME_OVERRIDE}"
	fi
	if [[ -n "${MAIN_BRANCH_OVERRIDE}" ]]; then
		STEAM_MAIN_BRANCH="${MAIN_BRANCH_OVERRIDE}"
	fi
	if [[ -n "${PLAYTEST_BRANCH_OVERRIDE}" ]]; then
		STEAM_PLAYTEST_BRANCH="${PLAYTEST_BRANCH_OVERRIDE}"
	fi
}

validate_environment() {
	[[ "$(uname -s)" == "Darwin" ]] || fail "This script is intended to run on macOS."
	[[ -x "${GODOT_BINARY}" ]] || fail "Godot binary not found or not executable: ${GODOT_BINARY}"
	command -v rsync >/dev/null 2>&1 || fail "Missing required command: rsync"
	command -v strings >/dev/null 2>&1 || fail "Missing required command: strings"
}

steamcmd_requires_rosetta() {
	[[ "${HOST_ARCH}" == "arm64" ]]
}

rosetta_available() {
	arch -x86_64 /usr/bin/true >/dev/null 2>&1
}

ensure_rosetta() {
	if ! steamcmd_requires_rosetta; then
		return
	fi
	if rosetta_available; then
		return
	fi

	log "Apple Silicon detected and SteamCMD is Intel-only. Installing Rosetta 2."
	/usr/sbin/softwareupdate --install-rosetta --agree-to-license

	if ! rosetta_available; then
		fail "Rosetta 2 installation did not succeed, so SteamCMD still cannot run."
	fi
}

run_steamcmd() {
	local -a args=("$@")

	if steamcmd_requires_rosetta; then
		ensure_rosetta
		(
			cd "${STEAMCMD_DIR}"
			arch -x86_64 /bin/bash "./steamcmd.sh" "${args[@]}"
		)
		return
	fi

	(
		cd "${STEAMCMD_DIR}"
		bash "./steamcmd.sh" "${args[@]}"
	)
}

select_targets() {
	local raw item
	for raw in ${TARGETS_CSV//,/ }; do
		item="$(normalize_csv_item "${raw}")"
		case "${item}" in
			main)
				TARGET_MAIN=1
				;;
			playtest)
				TARGET_PLAYTEST=1
				;;
			'')
				;;
			*)
				fail "Unsupported target '${raw}'. Use main and/or playtest."
				;;
		esac
	done

	if [[ "${TARGET_MAIN}" -eq 0 && "${TARGET_PLAYTEST}" -eq 0 ]]; then
		fail "No valid targets selected."
	fi
}

enable_platform() {
	case "$1" in
		macos)
			EXPORT_MACOS=1
			;;
		windows)
			EXPORT_WINDOWS=1
			;;
		linux)
			EXPORT_LINUX=1
			;;
		*)
			fail "Unsupported platform '$1'."
			;;
	esac
}

target_has_platform() {
	local target="$1"
	local platform="$2"
	local depot_id="0"
	case "${target}:${platform}" in
		main:macos)
			depot_id="${STEAM_MAIN_DEPOT_MACOS}"
			;;
		main:windows)
			depot_id="${STEAM_MAIN_DEPOT_WINDOWS}"
			;;
		main:linux)
			depot_id="${STEAM_MAIN_DEPOT_LINUX}"
			;;
		playtest:macos)
			depot_id="${STEAM_PLAYTEST_DEPOT_MACOS}"
			;;
		playtest:windows)
			depot_id="${STEAM_PLAYTEST_DEPOT_WINDOWS}"
			;;
		playtest:linux)
			depot_id="${STEAM_PLAYTEST_DEPOT_LINUX}"
			;;
	esac

	is_positive_int "${depot_id}"
}

validate_unique_target_depots() {
	local target="$1"
	local seen=""
	local platform depot_id token

	for platform in macos windows linux; do
		if ! platform_enabled "${platform}"; then
			continue
		fi
		depot_id="$(target_depot_id "${target}" "${platform}")"
		if ! is_positive_int "${depot_id}"; then
			continue
		fi
		token=" ${depot_id} "
		if [[ "${seen}" == *"${token}"* ]]; then
			fail "Target '${target}' has the same depot ID (${depot_id}) configured for multiple platforms. This script exports separate macOS/Windows/Linux binaries, so it expects one unique depot per platform for each app. Create separate depots in Steamworks (for example macOS, Windows, Linux) and set their OS filters there."
		fi
		seen="${seen}${depot_id} "
	done
}

select_platforms() {
	local raw item

	if [[ "$(normalize_csv_item "${PLATFORMS_CSV}")" == "auto" ]]; then
		if [[ "${TARGET_MAIN}" -eq 1 ]]; then
			target_has_platform main macos && EXPORT_MACOS=1
			target_has_platform main windows && EXPORT_WINDOWS=1
			target_has_platform main linux && EXPORT_LINUX=1
		fi
		if [[ "${TARGET_PLAYTEST}" -eq 1 ]]; then
			target_has_platform playtest macos && EXPORT_MACOS=1
			target_has_platform playtest windows && EXPORT_WINDOWS=1
			target_has_platform playtest linux && EXPORT_LINUX=1
		fi
	else
		for raw in ${PLATFORMS_CSV//,/ }; do
			item="$(normalize_csv_item "${raw}")"
			case "${item}" in
				macos|windows|linux)
					enable_platform "${item}"
					;;
				'')
					;;
				*)
					fail "Unsupported platform '${raw}'. Use macos, windows, linux, or auto."
					;;
			esac
		done
	fi

	if [[ "${EXPORT_MACOS}" -eq 0 && "${EXPORT_WINDOWS}" -eq 0 && "${EXPORT_LINUX}" -eq 0 ]]; then
		fail "No export platforms selected. Fill in depot IDs or pass --platforms explicitly."
	fi
}

platform_list_csv() {
	local result=""
	if [[ "${EXPORT_MACOS}" -eq 1 ]]; then
		result="macos"
	fi
	if [[ "${EXPORT_WINDOWS}" -eq 1 ]]; then
		if [[ -n "${result}" ]]; then
			result="${result},"
		fi
		result="${result}windows"
	fi
	if [[ "${EXPORT_LINUX}" -eq 1 ]]; then
		if [[ -n "${result}" ]]; then
			result="${result},"
		fi
		result="${result}linux"
	fi
	printf '%s' "${result}"
}

build_description() {
	if [[ -n "${DESC_OVERRIDE}" ]]; then
		printf '%s' "${DESC_OVERRIDE}"
		return
	fi

	local git_sha="no-git"
	local git_state="clean"
	local timestamp
	timestamp="$(date '+%Y-%m-%d %H:%M:%S %Z')"

	if git -C "${PROJECT_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
		git_sha="$(git -C "${PROJECT_ROOT}" rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
		if ! git -C "${PROJECT_ROOT}" diff --quiet --ignore-submodules HEAD -- >/dev/null 2>&1; then
			git_state="dirty"
		fi
	fi

	printf '%s | %s | %s | %s' "${timestamp}" "${git_sha}" "${git_state}" "$(platform_list_csv)"
}

godot_version_raw() {
	"${GODOT_BINARY}" --version | head -n1
}

godot_template_version() {
	printf '%s' "$(godot_version_raw)" | cut -d'.' -f1-4
}

godot_release_tag() {
	local version
	version="$(godot_template_version)"
	printf '%s' "${version}" | awk -F. '{ printf "%s.%s.%s-%s", $1, $2, $3, $4 }'
}

godot_template_dir() {
	printf '%s/Library/Application Support/Godot/export_templates/%s' "${HOME}" "$(godot_template_version)"
}

required_template_path() {
	local platform="$1"
	local template_dir
	template_dir="$(godot_template_dir)"
	case "${platform}" in
		macos)
			printf '%s/macos.zip' "${template_dir}"
			;;
		windows)
			printf '%s/windows_release_x86_64.exe' "${template_dir}"
			;;
		linux)
			printf '%s/linux_release.x86_64' "${template_dir}"
			;;
		*)
			fail "Unknown platform '${platform}' for template lookup."
			;;
	esac
}

ensure_godot_templates() {
	local needs_download=0
	local template_dir release_tag archive_name archive_url

	if [[ "${EXPORT_MACOS}" -eq 1 && ! -f "$(required_template_path macos)" ]]; then
		needs_download=1
	fi
	if [[ "${EXPORT_WINDOWS}" -eq 1 && ! -f "$(required_template_path windows)" ]]; then
		needs_download=1
	fi
	if [[ "${EXPORT_LINUX}" -eq 1 && ! -f "$(required_template_path linux)" ]]; then
		needs_download=1
	fi

	if [[ "${needs_download}" -eq 0 ]]; then
		return
	fi

	template_dir="$(godot_template_dir)"
	release_tag="$(godot_release_tag)"
	archive_name="Godot_v${release_tag}_export_templates.tpz"
	archive_url="${GODOT_EXPORT_TEMPLATES_URL:-https://github.com/godotengine/godot/releases/download/${release_tag}/${archive_name}}"

	log "Godot export templates are missing. Downloading ${archive_name}."
	log "This is a large one-time download for Godot ${release_tag}."

	local tmp_dir archive_path unpack_dir template_source
	tmp_dir="$(mktemp -d)"
	archive_path="${tmp_dir}/${archive_name}"
	unpack_dir="${tmp_dir}/unpacked"

	curl -L --fail -o "${archive_path}" "${archive_url}"
	unzip -q "${archive_path}" -d "${unpack_dir}"
	template_source="$(find "${unpack_dir}" -maxdepth 2 -type d -name templates | head -n1)"
	[[ -n "${template_source}" ]] || fail "Could not find the templates directory inside ${archive_name}."

	ensure_dir "$(dirname "${template_dir}")"
	rm -rf "${template_dir}"
	mv "${template_source}" "${template_dir}"
	rm -rf "${tmp_dir}"

	log "Installed Godot export templates into ${template_dir}."
}

ensure_steamcmd() {
	if [[ -x "${STEAMCMD_SH}" ]]; then
		return
	fi

	log "Downloading SteamCMD for macOS."
	ensure_dir "${STEAMCMD_DIR}"

	local tmp_dir archive_path
	tmp_dir="$(mktemp -d)"
	archive_path="${tmp_dir}/steamcmd_osx.tar.gz"

	curl -L --fail -o "${archive_path}" "${STEAMCMD_URL}"
	tar -xzf "${archive_path}" -C "${STEAMCMD_DIR}"
	rm -rf "${tmp_dir}"
	chmod +x "${STEAMCMD_SH}"

	log "Bootstrapping SteamCMD."
	run_steamcmd +quit >/dev/null
}

macos_output_path() {
	printf '%s/macos/%s' "${CONTENT_ROOT}" "${STEAM_MACOS_APP_NAME}"
}

windows_output_path() {
	printf '%s/windows/%s' "${CONTENT_ROOT}" "${STEAM_WINDOWS_EXECUTABLE_NAME}"
}

linux_output_path() {
	printf '%s/linux/%s' "${CONTENT_ROOT}" "${STEAM_LINUX_EXECUTABLE_NAME}"
}

staging_output_path() {
	local platform="$1"
	case "${platform}" in
		macos)
			printf '%s/macos/%s' "${EXPORT_STAGING_ROOT}" "${STEAM_MACOS_APP_NAME}"
			;;
		windows)
			printf '%s/windows/%s' "${EXPORT_STAGING_ROOT}" "${STEAM_WINDOWS_EXECUTABLE_NAME}"
			;;
		linux)
			printf '%s/linux/%s' "${EXPORT_STAGING_ROOT}" "${STEAM_LINUX_EXECUTABLE_NAME}"
			;;
		*)
			fail "Unsupported export platform '${platform}'."
			;;
	esac
}

export_platform() {
	local platform="$1"
	local preset_name staging_path staging_parent_dir
	case "${platform}" in
		macos)
			preset_name="Steam macOS"
			;;
		windows)
			preset_name="Steam Windows"
			;;
		linux)
			preset_name="Steam Linux"
			;;
		*)
			fail "Unsupported export platform '${platform}'."
			;;
	esac
	staging_path="$(staging_output_path "${platform}")"
	staging_parent_dir="$(dirname "${staging_path}")"

	log "Exporting ${platform} build with preset '${preset_name}'."
	rm -rf "${staging_parent_dir}"
	ensure_dir "${staging_parent_dir}"
	(
		cd "${EXPORT_PROJECT_ROOT}"
		"${GODOT_BINARY}" --headless --path . --export-release "${preset_name}" "${staging_path}"
	)
	if [[ "${platform}" == "linux" && -f "${staging_path}" ]]; then
		chmod +x "${staging_path}"
	fi
}

sync_staged_platform_output() {
	local platform="$1"
	local output_path parent_dir staging_path staging_parent_dir
	case "${platform}" in
		macos)
			output_path="$(macos_output_path)"
			;;
		windows)
			output_path="$(windows_output_path)"
			;;
		linux)
			output_path="$(linux_output_path)"
			;;
		*)
			fail "Unsupported export platform '${platform}'."
			;;
	esac
	parent_dir="$(dirname "${output_path}")"
	staging_path="$(staging_output_path "${platform}")"
	staging_parent_dir="$(dirname "${staging_path}")"
	rm -rf "${parent_dir}"
	ensure_dir "${parent_dir}"
	cp -R "${staging_parent_dir}/." "${parent_dir}/"
	if [[ "${platform}" == "linux" && -f "${output_path}" ]]; then
		chmod +x "${output_path}"
	fi
}

ensure_export_outputs_exist() {
	if [[ "${EXPORT_MACOS}" -eq 1 && ! -d "$(macos_output_path)" ]]; then
		fail "Missing macOS export at $(macos_output_path). Run without --upload-only first."
	fi
	if [[ "${EXPORT_WINDOWS}" -eq 1 && ! -f "$(windows_output_path)" ]]; then
		fail "Missing Windows export at $(windows_output_path). Run without --upload-only first."
	fi
	if [[ "${EXPORT_LINUX}" -eq 1 && ! -f "$(linux_output_path)" ]]; then
		fail "Missing Linux export at $(linux_output_path). Run without --upload-only first."
	fi
}

pck_search_root() {
	local platform="$1"
	case "${platform}" in
		macos)
			printf '%s/Contents/Resources' "$(macos_output_path)"
			;;
		windows)
			dirname "$(windows_output_path)"
			;;
		linux)
			dirname "$(linux_output_path)"
			;;
		*)
			fail "Unsupported export platform '${platform}'."
			;;
	esac
}

validate_exported_pck() {
	local platform="$1"
	local search_root pck_paths pck_path matches
	search_root="$(pck_search_root "${platform}")"
	[[ -d "${search_root}" ]] || fail "Missing ${platform} PCK search root: ${search_root}"
	pck_paths="$(find "${search_root}" -maxdepth 1 -type f -name '*.pck' -print)"
	[[ -n "${pck_paths}" ]] || fail "Missing ${platform} PCK under ${search_root}"

	while IFS= read -r pck_path; do
		[[ -n "${pck_path}" ]] || continue
		matches="$(strings -a "${pck_path}" | grep -E "${DEV_EXPORT_PATH_PATTERN}" | head -n 10 || true)"
		if [[ -n "${matches}" ]]; then
			fail "Exported ${platform} PCK includes development-only resources: ${matches//$'\n'/, }"
		fi
	done <<< "${pck_paths}"
}

validate_exported_content() {
	if [[ "${EXPORT_MACOS}" -eq 1 ]]; then
		validate_exported_pck macos
	fi
	if [[ "${EXPORT_WINDOWS}" -eq 1 ]]; then
		validate_exported_pck windows
	fi
	if [[ "${EXPORT_LINUX}" -eq 1 ]]; then
		validate_exported_pck linux
	fi
}

target_app_id() {
	case "$1" in
		main)
			printf '%s' "${STEAM_MAIN_APP_ID}"
			;;
		playtest)
			printf '%s' "${STEAM_PLAYTEST_APP_ID}"
			;;
		*)
			fail "Unknown target '$1'."
			;;
	esac
}

target_branch() {
	case "$1" in
		main)
			printf '%s' "${STEAM_MAIN_BRANCH}"
			;;
		playtest)
			printf '%s' "${STEAM_PLAYTEST_BRANCH}"
			;;
		*)
			fail "Unknown target '$1'."
			;;
	esac
}

target_depot_id() {
	local target="$1"
	local platform="$2"
	case "${target}:${platform}" in
		main:macos)
			printf '%s' "${STEAM_MAIN_DEPOT_MACOS}"
			;;
		main:windows)
			printf '%s' "${STEAM_MAIN_DEPOT_WINDOWS}"
			;;
		main:linux)
			printf '%s' "${STEAM_MAIN_DEPOT_LINUX}"
			;;
		playtest:macos)
			printf '%s' "${STEAM_PLAYTEST_DEPOT_MACOS}"
			;;
		playtest:windows)
			printf '%s' "${STEAM_PLAYTEST_DEPOT_WINDOWS}"
			;;
		playtest:linux)
			printf '%s' "${STEAM_PLAYTEST_DEPOT_LINUX}"
			;;
		*)
			fail "Unknown target/platform combination '${target}:${platform}'."
			;;
	esac
}

target_builds_url() {
	printf 'https://partner.steamgames.com/apps/builds/%s' "$(target_app_id "$1")"
}

platform_enabled() {
	case "$1" in
		macos)
			[[ "${EXPORT_MACOS}" -eq 1 ]]
			;;
		windows)
			[[ "${EXPORT_WINDOWS}" -eq 1 ]]
			;;
		linux)
			[[ "${EXPORT_LINUX}" -eq 1 ]]
			;;
		*)
			return 1
			;;
	esac
}

write_depot_script() {
	local target="$1"
	local platform="$2"
	local depot_id="$3"
	local depot_script_path="$4"
	local content_root local_path depot_path

	case "${platform}" in
		macos)
			content_root="$(dirname "$(macos_output_path)")"
			local_path="*"
			depot_path="."
			;;
		windows)
			content_root="$(dirname "$(windows_output_path)")"
			local_path="*"
			depot_path="."
			;;
		linux)
			content_root="$(dirname "$(linux_output_path)")"
			local_path="*"
			depot_path="."
			;;
		*)
			fail "Unknown platform '${platform}' while writing depot script."
			;;
	esac

	cat > "${depot_script_path}" <<EOF
"DepotBuild"
{
	"DepotID" "$(vdf_escape "${depot_id}")"
	"ContentRoot" "$(vdf_escape "${content_root}")"
	"FileMapping"
	{
		"LocalPath" "${local_path}"
		"DepotPath" "${depot_path}"
		"recursive" "1"
	}
}
EOF
}

write_app_build_script() {
	local target="$1"
	local branch app_id build_desc app_script_path output_dir depot_script_path
	local set_live_line=""
	local depots_block=""
	local platform depot_id

	app_id="$(target_app_id "${target}")"
	branch="$(target_branch "${target}")"
	build_desc="$(build_description) | ${target}"
	app_script_path="${STEAMPIPE_SCRIPT_ROOT}/app_build_${target}.vdf"
	output_dir="${STEAMPIPE_OUTPUT_ROOT}/${target}"

	is_positive_int "${app_id}" || fail "Missing ${target} App ID in ${CONFIG_PATH}."

	ensure_dir "${STEAMPIPE_SCRIPT_ROOT}"
	ensure_dir "${output_dir}"

	for platform in macos windows linux; do
		if ! platform_enabled "${platform}"; then
			continue
		fi
		depot_id="$(target_depot_id "${target}" "${platform}")"
		if ! is_positive_int "${depot_id}"; then
			log "Skipping ${target}/${platform}: no depot ID configured in ${CONFIG_PATH}."
			continue
		fi
		depot_script_path="${STEAMPIPE_SCRIPT_ROOT}/depot_build_${target}_${platform}.vdf"
		write_depot_script "${target}" "${platform}" "${depot_id}" "${depot_script_path}"
		depots_block="${depots_block}
		\"${depot_id}\" \"$(vdf_escape "${depot_script_path}")\""
	done

	[[ -n "${depots_block}" ]] || fail "No depot IDs configured for target '${target}' across the selected platforms."

	if [[ -n "${branch}" && "${branch}" != "default" ]]; then
		set_live_line=$'\t'"\"SetLive\" \"$(vdf_escape "${branch}")\""$'\n'
	fi

	cat > "${app_script_path}" <<EOF
"AppBuild"
{
	"AppID" "$(vdf_escape "${app_id}")"
	"Desc" "$(vdf_escape "${build_desc}")"
	"BuildOutput" "$(vdf_escape "${output_dir}")"
	"Preview" "${PREVIEW_BUILD}"
${set_live_line}	"ContentRoot" "$(vdf_escape "${CONTENT_ROOT}")"
	"Depots"
	{
${depots_block}
	}
}
EOF

	printf '%s' "${app_script_path}"
}

run_steamcmd_upload() {
	local target="$1"
	local branch app_build_path
	app_build_path="$(write_app_build_script "${target}")"
	branch="$(target_branch "${target}")"

	if [[ "${DRY_RUN}" -eq 1 ]]; then
		log "Dry run: generated ${app_build_path}"
		if [[ -n "${branch}" && "${branch}" != "default" ]]; then
			log "Dry run: this build would auto-set branch '${branch}' live."
		else
			log "Dry run: this build would require a manual Set Live click for the default branch."
		fi
		return
	fi

	[[ -n "${STEAM_BUILDER_USERNAME}" ]] || fail "Set STEAM_BUILDER_USERNAME in ${CONFIG_PATH} or pass --steam-username."

	log "Uploading ${target} build through SteamCMD."
	if [[ -n "${STEAM_GUARD_CODE:-}" ]]; then
		run_steamcmd +set_steam_guard_code "${STEAM_GUARD_CODE}" +login "${STEAM_BUILDER_USERNAME}" +run_app_build "${app_build_path}" +quit
	else
		run_steamcmd +login "${STEAM_BUILDER_USERNAME}" +run_app_build "${app_build_path}" +quit
	fi

	if [[ -n "${branch}" && "${branch}" != "default" ]]; then
		log "Uploaded ${target} build and requested SetLive for beta branch '${branch}'."
	else
		log "Uploaded ${target} build. Steam requires a manual Set Live for the default branch:"
		log "  $(target_builds_url "${target}")"
	fi
}

main() {
	parse_args "$@"
	load_config
	validate_environment
	select_targets
	select_platforms

	log "Selected targets: ${TARGETS_CSV}"
	log "Selected platforms: $(platform_list_csv)"
	if [[ "${TARGET_MAIN}" -eq 1 ]]; then
		validate_unique_target_depots main
	fi
	if [[ "${TARGET_PLAYTEST}" -eq 1 ]]; then
		validate_unique_target_depots playtest
	fi

	if [[ "${MODE}" != "upload-only" ]]; then
		ensure_godot_templates
		prepare_export_project
		rm -rf "${CONTENT_ROOT}" "${EXPORT_STAGING_ROOT}"
		ensure_dir "${CONTENT_ROOT}"
		if [[ "${EXPORT_MACOS}" -eq 1 ]]; then
			export_platform macos
		fi
		if [[ "${EXPORT_WINDOWS}" -eq 1 ]]; then
			export_platform windows
		fi
		if [[ "${EXPORT_LINUX}" -eq 1 ]]; then
			export_platform linux
		fi
		if [[ "${EXPORT_MACOS}" -eq 1 ]]; then
			sync_staged_platform_output macos
		fi
		if [[ "${EXPORT_WINDOWS}" -eq 1 ]]; then
			sync_staged_platform_output windows
		fi
		if [[ "${EXPORT_LINUX}" -eq 1 ]]; then
			sync_staged_platform_output linux
		fi
		ensure_export_outputs_exist
		validate_exported_content
	fi

	if [[ "${MODE}" != "export-only" ]]; then
		ensure_export_outputs_exist
		validate_exported_content
		if [[ "${DRY_RUN}" -eq 0 ]]; then
			ensure_steamcmd
		fi
		if [[ "${TARGET_MAIN}" -eq 1 ]]; then
			run_steamcmd_upload main
		fi
		if [[ "${TARGET_PLAYTEST}" -eq 1 ]]; then
			run_steamcmd_upload playtest
		fi
	fi

	log "Done."
}

main "$@"
