#!/usr/bin/env python3
"""Regenerate the audited card inventory in spec/card_targeting.md.

Input is the JSON that tests/card_targeting_audit_test.gd writes to
user://card_targeting_audit.json (the runner prints its absolute path). Rows
cover live cards in data/cards.json order; retired ids stay in the audit for
save compatibility but are summarised, not listed.

    python3 tools/card_targeting_inventory.py <card_targeting_audit.json>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "card_targeting.md"
CARDS = ROOT / "data" / "cards.json"
START = "<!-- card-inventory:start -->"
END = "<!-- card-inventory:end -->"


def inventory(audit: dict, cards: dict) -> str:
    rows = {str(row["id"]): row for row in audit.get("cards", [])}
    live = [card_id for card_id, card in cards.items() if not card.get("retired", False)]
    retired = [card_id for card_id, card in cards.items() if card.get("retired", False)]
    missing = [card_id for card_id in live if card_id not in rows]
    if missing:
        raise SystemExit("audit JSON is missing live cards: %s" % ", ".join(missing))
    live_rows = [rows[card_id] for card_id in live]
    targetless = sum(1 for row in live_rows if row.get("targetless", False))
    targets = sum(int(row.get("targets_exercised", 0)) for row in live_rows)
    lines = [
        START,
        "Generated by `tools/card_targeting_inventory.py` from the audit JSON: %d live cards"
        " (%d self confirmations, %d with one board decision) and %s exercised targets."
        " The audit also replays the %d retired ids (%s), which resolve to their replacements."
        % (len(live_rows), targetless, len(live_rows) - targetless, "{:,}".format(targets), len(retired),
           ", ".join("`%s`" % card_id for card_id in retired)),
        "",
        "| Card | Effects | Board choice | Targets checked |",
        "| --- | --- | --- | ---: |",
    ]
    for card_id, row in zip(live, live_rows):
        name = str(cards[card_id].get("name", row.get("name", card_id)))
        effects = ", ".join(str(action) for action in row.get("actions", [])) or "none"
        choice = "Self confirmation" if row.get("targetless", False) else "One target"
        lines.append("| %s (`%s`) | %s | %s | %d |" % (name, card_id, effects, choice, int(row.get("targets_exercised", 0))))
    lines.append(END)
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__.strip())
        return 2
    audit = json.loads(Path(argv[1]).read_text())
    cards = json.loads(CARDS.read_text())
    text = SPEC.read_text()
    if START not in text or END not in text:
        raise SystemExit("%s lacks the %s / %s markers" % (SPEC, START, END))
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    SPEC.write_text(head + inventory(audit, cards) + tail)
    print("Updated %s" % SPEC.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
